$$
H = M \beta \frac{\sum \limits_{i \alpha} U_{i \alpha} W_{i \alpha} c^i}{\sum \limits_{i \alpha} W_{i \alpha} c^j}; \quad W_{i \alpha} = \exp(- \frac{\beta U_{i \alpha}}{\theta \gamma}); \quad \frac{\partial W_{i \alpha}}{\partial \theta} = \frac{\beta U_{i \alpha}}{\gamma \theta^2}W_{i \alpha}
$$

\begin{align}
\frac{\partial H}{\partial \theta} &=  M \beta \frac {\sum\limits_{i \alpha} c^i U_{i \alpha} {\partial W_{i \alpha}}/{\partial \theta} \sum\limits_j c^j W_j - \sum\limits_i c^i {\partial W_i}/{\partial \theta} \sum\limits_{i \alpha} U_{i \alpha}  W_{i \alpha}  c^i}{(\sum\limits_j c^j W_j)^2}\\
&= \frac{M \beta^2}{\gamma \theta^2} \frac {\sum\limits_{i \alpha} c^i U_{i \alpha}^2  W_{i \alpha} \sum\limits_j c^j W_j - \sum\limits_{i \alpha} c^i U_{i \alpha} W_{i \alpha} \sum\limits_{j \delta} U_{j \delta}  W_{j \delta}  c^i}{(\sum\limits_j c^j W_j)^2}\\
&= \frac{M \beta^2}{\gamma \theta^2} \frac{\sum\limits_{i \alpha} \sum\limits_{j \delta} c^{i+j} W_{i \alpha} W_{j \delta}  (U_{i \alpha}^2 - U_{i \alpha}U_{j \delta} )}{(\sum\limits_j c^j W_j)^2}
= \frac{M \beta^2}{\gamma \theta^2} \frac{\sum\limits_{i \alpha} \sum\limits_{j \delta} c^{i+j} W_{i \alpha} W_{j \delta}  (U_{j \delta}^2 - U_{i \alpha}U_{j \delta} )}{(\sum\limits_j c^j W_j)^2}\\
&= \frac{M \beta^2}{2 \gamma \theta^2} \frac{\sum\limits_{i \alpha} \sum\limits_{j \delta} c^{i+j} W_{i \alpha} W_{j \delta}  (U_{j \delta} - U_{i \alpha} )^2}{(\sum\limits_j c^j W_j)^2}
\end{align}

\begin{align}
\frac{\partial H}{\partial c} &= M \beta \frac{\sum\limits_{i \alpha} i c^{i-1} U_{i \alpha} W_{i \alpha} \sum\limits_{j \delta} c^j W_{j \delta} - \sum\limits_{i \alpha} c^i  U_{i \alpha} W_{i \alpha} \sum\limits_{j \delta} j c^{j-1} W_{j \delta} }{(\sum\limits_j c^j W_j)^2}\\
&= M \beta \frac{\sum\limits_{i \alpha} \sum\limits_{j \delta} U_{i \alpha} W_{i \alpha} W_{j \delta} c^{i+j-1} (i-j)}{(\sum\limits_j c^j W_j)^2}
= M \beta \frac{\sum\limits_{i \alpha} \sum\limits_{j \delta} U_{j \delta} W_{i \alpha} W_{j \delta} c^{i+j-1} (j-i)}{(\sum\limits_j c^j W_j)^2}\\
&= \frac{M \beta}{2} \frac{\sum\limits_{i \alpha} \sum\limits_{j \delta}  W_{i \alpha} W_{j \delta} c^{i+j-1} (i-j)(U_{i \alpha} - U_{j \delta})}{(\sum\limits_j c^j W_j)^2}
\end{align}


$$ x_1 = \frac{\sum\limits_i i c^i W_i}{k \sum\limits_j c^j W_j}    $$

\begin{align}
\frac{\partial x1}{\partial \theta} &=  \frac{\sum\limits_i i c^i \partial W_i/\partial \theta \sum\limits_j c^j W_j - \sum\limits_j j c^j W_j \sum\limits_i c^i \partial W_i/\partial \theta}{k (\sum\limits_j c^j W_j )^2} \\
&=  \frac{\sum\limits_{i \alpha} i c^i \partial W_{i \alpha}/\partial \theta \sum\limits_{j \delta} c^j W_{j \delta} - \sum\limits_{j \delta} j c^j W_{j \delta} \sum\limits_{i \alpha} c^i \partial W_{i \alpha}/\partial \theta}{k(\sum\limits_j c^j W_{j \delta} )^2 } \\
&= \frac{\beta}{\gamma \theta^2} \frac{\sum\limits_{i \alpha} \sum\limits_{j \delta}(i-j) c^{i+j} U_{i \alpha} W_{i \alpha}  W_{j \delta}  }{k(\sum\limits_j c^j W_j )^2 } \\
&= \frac{\beta}{2 \gamma \theta^2} \frac{\sum\limits_{i \alpha} \sum\limits_{j \delta}(i-j) c^{i+j} (U_{i \alpha} - U_{j \delta})W_{i \alpha}  W_{j \delta}  }{k(\sum\limits_j c^j W_j )^2 } 
\end{align}

\begin{align}
\frac{\partial x1}{\partial c} &= \frac{\sum\limits_{i j} (i^2-i*j) W_i W_j c^{i+j-1} }{k(\sum\limits_j c^j W_j)^2} = 
\frac{1}{2}\frac{\sum\limits_{i j} (i-j)^2 W_i W_j c^{i+j-1} }{k(\sum\limits_j c^j W_j)^2}\\
\frac{dc}{d \theta} &= - \frac{\partial x1}{\partial \theta} / \frac{\partial x1}{\partial c} = -\frac{\beta}{ \gamma \theta^2} \frac{\sum\limits_{i \alpha} \sum\limits_{j \delta}(i-j) c^{i+j} (U_{i \alpha} - U_{j \delta})W_{i \alpha}  W_{j \delta}  }{\sum\limits_{i j} (i-j)^2 W_i W_j c^{i+j-1} }
\end{align}

Now we consider FCC case with tetrahedron as cell. In this case $U_{i \alpha}$ and $W_{i \alpha}$ do not depend on $\alpha$:
$$
U_{i \alpha} \equiv U_i; \quad W_i = \sum_i W_{i \alpha} = {k \choose i} W_{i 1} = {k \choose i} \exp(- \frac{\beta U_i}{\gamma \theta})
$$

Enthalpy (from TISR_p1):
$$
H = M \beta \frac{\sum\limits_i U_i W_i c^i}{\sum\limits_j W_j c^j}; \quad \frac{\partial H}{\partial \theta} =  \frac{M \beta^2}{2 \gamma \theta^2} \frac{\sum\limits_i \sum\limits_j c^{i+j} W_i W_j  (U_j - U_i )^2}{(\sum\limits_j c^j W_j)^2}; \quad \frac{\partial H}{\partial c} =  \frac{M \beta}{2} \frac{\sum\limits_i \sum\limits_j  W_i W_j c^{i+j-1} (i-j)(U_i - U_j)}{(\sum\limits_j c^j W_j)^2}
$$

\begin{align}
x_1 = \frac{\sum\limits_i i c^i W_i}{k \sum\limits_j c^j W_j} ; \qquad 
\frac{\partial x1}{\partial \theta} 
&= \frac{\beta}{2 \gamma \theta^2} \frac{\sum\limits_i \sum\limits_j(i-j) c^{i+j} (U_i - U_j)W_i  W_j  }{k(\sum\limits_j c^j W_j )^2 } ; \quad 
\frac{\partial x1}{\partial c}  = 
\frac{1}{2}\frac{\sum\limits_{i j} (i-j)^2 W_i W_j c^{i+j-1} }{k(\sum\limits_j c^j W_j)^2}\\
\frac{dc}{d \theta} &= - \frac{\partial x1}{\partial \theta} / \frac{\partial x1}{\partial c} 
= -\frac{\beta}{ \gamma \theta^2} \frac{\sum\limits_i \sum\limits_j(i-j) c^{i+j} (U_i - U_j)W_i  W_j  }{\sum\limits_{i j} (i-j)^2 W_i W_j c^{i+j-1} }
\end{align}

\begin{align}
cW = \sum\limits_i c^i W_i; \quad xW = \sum\limits_i i c^i W_i; \quad x2W = \sum\limits_i i i c^i W_i; \quad UW = \sum\limits_i c^i U_i W_i; \quad U2W = \sum\limits_i c^i U_i U_i W_i; \quad xUW = \sum\limits_i i c^i U_i W_i; 
\end{align}

\begin{align}
H = M \beta \frac{UW}{cW}; \quad \frac{\partial H}{\partial \theta} = \frac{M \beta^2}{\gamma \theta^2} \frac{(U2W)(cW) - (UW)^2}{(cW)^2}; \quad \frac{\partial H}{\partial c} = M \beta \frac{(xUW)(cW) - (UW)(xW)}{c (cW)^2}
\end{align}

$$ x1 = \frac{xW}{k (cW)}; \quad \frac{dc}{d \theta} = - \frac{c \beta}{\gamma \theta^2} \frac{(xUW)(cW) - (UW)(xW)}{(x2W)(cW) - (xW)^2}
$$

$$
\sum_{i=0}^{n} \left(a + m x{\left (i \right )} - y{\left (i \right )}\right)^{2}
$$

In [10]:
import numpy as np
import ipywidgets as wdg
import matplotlib.pyplot as plt


In [11]:
z,k, m, beta = 12, 4, 6, 4
gamma = 4.
#theta = 10
I = ([0,1,2,3,4])
Cki = np.array([1,4,6,4,1])                          #combinatoric coeff

cW = np.array([1,1,1,1,1])
def fUW(U1, U2, U3, theta):
#    print(U1, U2, U3)
#    U2T[1] = 3*U1; U2T[2] = 4*U2; U2T[3] = 3*U3
    U = np.array([0, 3*U1, 4*U2, 3*U3, 0]) 
    U2T = U / theta
    W = np.exp( - U2T * beta / gamma)
    W = W*Cki
#    print(U2T)
    return U, U2T, W
U, U2T, W = fUW(20,30,40, 10000)                                   # instead of U using U2T = U / theta
U, U2T, W

(array([  0,  60, 120, 120,   0]),
 array([ 0.   ,  0.006,  0.012,  0.012,  0.   ]),
 array([ 1.        ,  3.97607186,  5.92843028,  3.95228685,  1.        ]))

In [12]:
def cp(c, u, U2T, W):
    ci = ([1,1,1,1,1])
    ci[1] = c;     ci[2] = c*ci[1]  ;  ci[3] = c*ci[2];    ci[4] = c*ci[3]
    cW = ci*W; xW = I*cW; x2W = I*xW; UW = U2T*cW; uW = u*cW; U2W = U2T*UW; xUW = I*UW
    scW = np.sum(cW); sxW = np.sum(xW); sx2W = np.sum(x2W); sUW = np.sum(UW); suW = np.sum(uW); sU2W = np.sum(U2W);  sxUW = np.sum(xUW)
    dHdT = beta*beta / k / gamma *(sU2W*scW - sUW*sUW) / scW /scW
    dHdc = beta / k *(sxUW*scW - sUW*sxW )/scW/scW                                 # divided by theta & multiplied by c
    dcdT = - beta/gamma * (sxUW*scW - sUW*sxW )/(sx2W*scW - sxW*sxW)               # divided by c
    Cp = dHdT + dHdc*dcdT; x1 = sxW / scW / k
    H = beta / k * suW / scW                                                       # using U rather than u/theta
#    print(W, U2W, UW,U2W,sUW,sU2W)
#    print (ci, W, cW, xW, x2W, UW, U2W, xUW, scW, sxW, sx2W, sUW, sU2W, sxUW, Cp, x1, dHdT, dcdT, H)
    return Cp, H

U, U2T, W = fUW(20,30,40, 10000)   
cp(1,U, U2T, W)

In [13]:
from scipy.optimize import fsolve
def c2x1(c, *extr):
    ci = ([1,1,1,1,1])
    x1, W = extr
    ci[1] = c;     ci[2] = c*ci[1]  ;  ci[3] = c*ci[2];    ci[4] = c*ci[3]
    cW = ci*W; xW = I*cW; scW = np.sum(cW); sxW = np.sum(xW)
    return sxW / scW / k - x1

def x1_c(c2x1, x1, W):
    c = x1 / (1-x1)
    return fsolve(c2x1, c, (x1, W))

x1 = 0.5
TT = np.linspace(.1001, 11.0001, 101)
HH = np.zeros(100)
CCp = np.zeros(100)
xT = np.zeros(100)
#print(TT)
def HCp(U1,U2,U3):
   
    for i in np.arange(100):
        u, U2T, W = fUW(U1,U2,U3, TT[i])  
        ([c])=x1_c(c2x1, x1, W)
        (CCp[i], HH[i]) = cp(c, u, U2T, W)
        xT[i] = TT[i]
#        print(i, c, xT[i], CCp[i], HH[i], W, U2T)

    fig = plt.figure(figsize=(5,10))
    fig.add_subplot(211)
    plt.plot(xT, HH)
    plt.xlim(0,10)
    plt.ylabel(r'H',fontsize=15 );
    fig.add_subplot(212)
    plt.plot(xT, CCp)
#     plt.plot(y1_1, fy*0, linewidth = 1)
#     plt.ylim(-1, 1)
    plt.xlim(0,10)
    plt.xlabel(r'T',fontsize=15 );
    plt.ylabel(r'$C_v$',fontsize=15 );
    plt.show()
    fig.savefig('E:\\GIT\\TISR1\\notebooks\\heat_capacity.pdf', format='pdf', dpi=1200, bbox_inches='tight') 
    
    print(U2T)

#print(b1_min0, b1_max0)
U1 = wdg.FloatSlider(min=-2.9999, max=10.0001, value = 2.0001 )
U2 = wdg.FloatSlider(min=-2.9999, max=10.0001, value = 2.0001 )
U3 = wdg.FloatSlider(min=-2.9999, max=10.0001, value = 2.0001 )
wdg.interactive(HCp, U1=U1,U2=U2,U3=U3)
#cp(1, 0.5)

interactive(children=(FloatSlider(value=2.0001, description='U1', max=10.0001, min=-2.9999), FloatSlider(value…

In [14]:
#print(HH, CCp)


In [15]:
c2x1(0.61782945, 0.3, W)